### ISSUE TITLE
Add galu1

### ISSUE THREAD

**Issue by captn3m0** [system76/tech-docs#109]
The old Galago Pro (https://web.archive.org/web/20150912073138/https://system76.com/laptops/galago) is not documented on the website.

**Comment by jacobgkau** [comment]
Thank you for opening an issue. While all current models are being documented at release, it is unlikely that models several generations old such as galu1 will be added to tech docs, at least in the immediate future.

The support team can still provide information and answer questions regarding the servicing of this model if you open a support ticket: https://support.system76.com/ 

What specific information do you need regarding this model?

**Comment by captn3m0** [comment]
Was facing some issues regarding boot, and the support website linked to the docs page  (this repo) for those.

It only boots once every 10 attempts or so, and only from the battery, and I can't figure out why.

Will open a support ticket.
