### ISSUE TITLE
Add base Thelio model

### ISSUE THREAD

**Issue by JoshAubrey** [system76/tech-docs#128]
Add documentation detailing base thelio model specs:
[https://system76.com/desktops/thelio](https://system76.com/desktops/thelio)

Missing from: [https://github.com/system76/tech-docs/tree/master/src/models](https://github.com/system76/tech-docs/tree/master/src/models)

Thanks!

**Comment by leviport** [comment]
This will be done starting with thelio-b3.

**Comment by storyaddict** [comment]
I'll be doing it sooner than that.

**Comment by storyaddict** [comment]
Will also address #82

**Comment by leviport** [comment]
I think this can be closed now that https://github.com/system76/tech-docs/pull/153 has been merged. 

To clarify my statement above, thelio-b4 and thelio-b3 were both released simultaneously (Alder Lake supports DDR4 and DDR5, so there was a model for each). There are still plans for thelio-b3, but there were a few things about thelio-b4 that made it higher priority than thelio-b3.
