### ISSUE TITLE
gaze17 DisplayPort 1.4 over USB-C support discrepancy.

### ISSUE THREAD

**Issue by Kennegh** [system76/tech-docs#159]
The store page (https://system76.com/laptops/gazelle) lists the 3060 model as being the only model to support DP over USB-C.

The Graphics section of the tech-doc (https://tech-docs.system76.com/models/gaze17/README.html) seems to imply both models support DP over USB-C, but the USB section for the 3050 models state that it does not support DP over USB-C at all.

**Comment by jacobgkau** [comment]
> the USB section for the 3050 models state that it does not support DP over USB-C at all.

This matches the store page saying only the 3060 supports it, and is not a discrepancy.

> The Graphics section of the tech-doc (https://tech-docs.system76.com/models/gaze17/README.html) seems to imply both models support DP over USB-C,

I agree some clarification could be used for that section.
