### ISSUE TITLE
Pang12 Missing Displayport Version

### ISSUE THREAD

**Issue by Aegor1998** [system76/tech-docs#165]
The displayport version for usb-c displayport mode is missing. Could this get fixed please.

**Comment by jacobgkau** [comment]
https://www.amd.com/en/product/11591 - AMD's product page for the CPU/GPU (APU) states that it supports DisplayPort 2.0, but also states that the maximum resolution/refresh rate is 4k @ 60 Hz, which is only half the maximum for DisplayPort 1.4. (Also, that page states the APU supports HDMI 2.1, but the pang12's motherboard is known to only support HDMI 2.0.)

We may need to check with the motherboard manufacturer to confirm what should be listed for this.

**Comment by Aegor1998** [comment]
That does not answer the question on what the laptop supports

**Comment by leviport** [comment]
@Aegor1998 Indeed. But it does clarify that we are working on it. Thank you for your patience.

**Comment by leviport** [comment]
@Aegor1998 the spec is DisplayPort 1.4. I'll open a pull request shortly.

**Comment by Aegor1998** [comment]
Thank you
