### ISSUE TITLE
Add Meerkat(meer7) to the tech-docs

### ISSUE THREAD

**Issue by GarnierAdrian** [system76/tech-docs#187]
Adding the Meerkat's new model and moving meer6 to Previous Models.

I currently have the updated text for the README.md, internal-overview and external-overview basing it on the following links:

https://www.intel.com/content/www/us/en/products/sku/121617/intel-nuc-12-pro-kit-nuc12wshi3/specifications.html
https://system76.com/desktops/meerkat

However, before adding old images to the git history or false information, I wanted to know what should I do for the repairs file and the images.

**Comment by jacobgkau** [comment]
Hello, thank you for setting that branch up. We typically take photos for the repairs page in our marketing team's photo room. I believe our QA lab currently has at least one meer7 I could use to do this. We currently have several other models we're working on documentation for, but I will get this added to the list.

If you keep your branch around and writable by maintainers, I will use it as a base when I get to this model.

@evam76 Could you add meer7 to the outstanding models on the internal project board?

**Comment by jacobgkau** [comment]
We don't want to reuse any images between models, just to be clear. Any copies of meer6 photos will need to be cleared out/replaced with meer7 photos before merging.

**Comment by GarnierAdrian** [comment]
My bad, I was thinking about copying the text when I wrote that. I understand the need for exact images of the model in the technical document. 

My thoughts were, since it's a relatively stable product, and the internals are mostly the same, the text description of the repair would be identical in many cases (like replacing ssd or ram) and maybe it would require small changes on other parts (like the description of the location of a panel screws). 

It's a minor thing anyway so if you prefer @jacobgkau I'll just leave it like that.

**Comment by jacobgkau** [comment]
You're correct, for the text, I would typically copy the previous model's file and then edit/update from there. It doesn't make too much of a difference whether you make the initial copy or I do.

**Comment by ahoneybun** [comment]
This has been added so I believe this can be closed:

https://github.com/system76/tech-docs/blob/master/src/models/meer7/README.md
