### ISSUE TITLE
Lemp12 doc section "Macronix MX25L25673G flash chip" seems weird

### ISSUE THREAD

**Issue by trevor87** [system76/tech-docs#223]
The docs for the Lemp12 state that it has a "Macronix MX25L25673G flash chip". Is this really correct?

Both my machine and the image in the docs (https://tech-docs.system76.com/models/lemp12/img/components-highlighted.webp) have a GigaDevice chip. Also the file https://github.com/system76/firmware-open/blob/master/models/lemp12/chip.txt contains the id for a gigadevice chip.

**Comment by jacobgkau** [comment]
The schematic diagram provided by the motherboard manufacturer includes the Macronix chip, I think that's where it came from:

![screenshot-2024-06-04-21-41-48](https://github.com/system76/tech-docs/assets/7199422/8a3dbb60-961b-4fd0-92a4-efcd9e43d8e9)

I'll double-check a lab unit and update this if necessary. (Seeing as it's a WSON-8 socket, I guess either chip might work in the system?)

**Comment by crawfxrd** [comment]
Whatever is in the schematics is likely only what Clevo used for the original design. They will seemingly use any compatible chip they have available (Macronix, Winbond, GigaDevice, and now unfortunately XMC). We have several cases of units of the same model using different flash chips (https://github.com/system76/firmware-open/issues/72).

**Comment by jacobgkau** [comment]
I guess we can start adding "(or equivalent)" to the flash chip spec.

**Comment by jacobgkau** [comment]
I can confirm at least one of our lab lemp12's has a `GigaDevice AJ2247 25B256EYIG UHJ814`. Seeing as the photo unit also had that, this could have just been a case of the schematic being incorrect/not updated properly from the lemp12.

**Comment by jackpot51** [comment]
Simce the flash chip often is changed maybe we should just remove that info.

**Comment by jacobgkau** [comment]
It still seems useful to document at least one known-compatible chip for each model, and to document the ones we're aware they shipped with. I think for now, we should just add a list of known chips with the "or equivalent" line, like we do with LCD panels.
