### ISSUE TITLE
Incorrect wiring for all nebula power buttons

### ISSUE THREAD

**Issue by ahoneybun** [system76/tech-docs#234]
In the following photos for the nebulas:

- https://tech-docs.system76.com/models/nebula19-1/img/front-daughterboard-connectors.webp
- https://tech-docs.system76.com/models/nebula36-1/img/front-daughterboard-connectors.webp
- https://tech-docs.system76.com/models/nebula49-1/img/front-daughterboard-connectors.webp

The cable pattern is Red, Black, Black, Blue but per this photo of the Spark:

- https://tech-docs.system76.com/models/thelio-spark-b1-n2/img/power-button-receptacle.webp

it should be Red, Black, Blue, Black. If you follow the photos of the nebula's the light on the button will turn on once the back switch is turned on but the button will not work. If the pattern is  Red, Black, Blue, Black when the button is only lit once it has been pressed and the system powers on.

**Comment by jacobgkau** [comment]
This cable is preinstalled, which means our mechanical engineering and assembly teams must have put all three of these systems together incorrectly before passing them off to me for documentation.

I want to confirm with those teams what's going on here before we make any corrections. nebula_io is a different board from thelio_io, and the actual color of the wires isn't really important so much as how the connections make their way all the way to the motherboard.

If they are actually incorrect, then we'll need to either get an updated build of each for a reshoot, or place a correction note on each page.

**Comment by leviport** [comment]
The order of the blue/black pair does not matter at all. The front button is a momentary switch, which has no polarity.

**Comment by jacobktm** [comment]
If it was going straight from the power button to the motherboard it wouldn't matter. I think it's also possible that if they made the same flip on the motherboard it could still work. Because of the IO board in the middle, though, it won't work if it's wired +|-|+|- on the motherboard to +|-|+|- on the IO Board and then +|-|+|- from the IO Board to +|-|-|+ on the power button. I remember while I was in build this was among the first things we would look for if the system didn't power on.

**Comment by leviport** [comment]
@jacobktm that was with thelio-io-v1 though, wasn't it? While I still find it surprising that a momentary switch could possibly have polarity like that, I feel like it definitely shouldn't be the case on thelio-io-v2 or the nebula IO board, which are the only varieties that will be found on Nebula-era cases.

**Comment by ahoneybun** [comment]
It did matter for me with the Nebula Io board so it is an issue at least in my experience.

**Comment by jacobktm** [comment]
@leviport you're right, it looks like that was the case with the old IO boards but these new ones don't care. I don't know what was happening with @ahoneybun's

**Comment by leviport** [comment]
Huh, the Nebula board should be even simpler.

**Comment by jacobgkau** [comment]
We can make the wiring consistent with Thelio next time we redo photos for a new version of Nebula. In the meantime, it sounds like the wiring polarity for this pair cannot cause an issue.
