### ISSUE TITLE
nebula 36 instructions unclear

### ISSUE THREAD

**Issue by DingusWyFy** [system76/tech-docs#241]
I'm writing this on my phone, so please forgive the formatting. And lack there of.

There is no "thinner" side for the fan bracket inside the cpu shroud. Is this supposed to mean the side with no flange? All the metal is the same thickness.

When following the instructions blindly for the first time, it appeared to me that I needed to rotate the orientation of the preinstalled be-quiet fan. Going through this linearly on mobile, without reading the entire document, the instructions seemed like my orientation was wrong.

I had more issues when I first received my case and tried assembling. I wish I took notes about my frustrations. The main point I remember was the instructions being verbose but not explicit. Reading them came off as, "we will address this later." But that hasn't come to fruition.

I am not well versed with Github, git, trying to help FOSS/open source projects either. I wanted to give it some time before I wrote about this, outside of a post on fosstodon. Writing while mad and extremely frustrated is going to do nobody any good.

Again, sorry for the improper format and lack of specific issues with answers.

**Comment by leviport** [comment]
Thank you for the feedback. It is indeed the side without the flange, circled in green below. "Thin" was not intended to refer to the gauge of the metal, but rather the width of the side piece. Perhaps "narrowest part without the flange" would be clearer?

![screenshot-2024-03-18-22-10-58](https://github.com/system76/tech-docs/assets/13512097/fc35faaa-6fd7-4492-8f48-b3a0f689b9a6)

**Comment by jacobgkau** [comment]
Perhaps we can just mark the side that's supposed to point into the duct similar to how @leviport circled it in that screenshot. Then we won't need to play word games to get people to understand which side it is.

You will need to point out any other issues specifically for them to be actionable. "Verbose but not explicit" is the opposite of what I aim for (within the limitations of describing mechanical assembly in text/photo format), and I'm afraid I don't know what other issues you might have run into with things not being explicit enough. (Even just looking at the above photo, it's difficult for me to imagine someone not being able to correctly guess which one we meant by "thinnest." It's the side with the least material.)

**Comment by jacobgkau** [comment]
Actually, before this photo, we instruct people to put the "thinnest side on the left" (for nebula36). Seeing as there's a photo, this makes me question even more how the instruction after the photo could be misinterpreted.

It also means that if this wasn't clear before, adding an arrow to the image wouldn't make it any more clear.
