### ISSUE TITLE
pang14: Broken URL

### ISSUE THREAD

**Issue by blakeridgway** [system76/tech-docs#264]
The Memory section for the Pang14 has a link for the LPDDR5 on-board memory that goes to a "No Results Found" page on Micron.

[Pang14 Overview](https://tech-docs.system76.com/models/pang14/README.html)

![image](https://github.com/user-attachments/assets/cb457478-ddfe-44c6-8794-2045d11a8624)

Links to the following page: https://www.micron.com/products/dram/lpdram/part-catalog/mt62f2g32d8dr-031-wt

Visiting that page returns the following page:

![image](https://github.com/user-attachments/assets/30b4e8b1-277e-46b8-8447-4f7eaf054a45)

**Comment by jacobgkau** [comment]
I was going to address this after the current Major section I'm working on is complete, but I've gotten busy enough with software stuff to delay that, so I'll just do it now.
