### ISSUE TITLE
Add thelio-major-b3

### ISSUE THREAD

**Issue by jackpot51** [system76/tech-docs#57]
- [ ] Add specs for thelio-major-b3 to https://tech-docs.system76.com/models/thelio-major-intel-and-amd/internal-overview.html
- [ ] Add exception for power button wiring on thelio-major-b3 to https://tech-docs.system76.com/models/thelio-major-intel-and-amd/internal-overview.html#motherboard-power-button

**Comment by grantdelozier** [comment]
Any update on this? I'm trying to judge whether my thelio-major-b3 mobo will support a second self-installed GPU (A6000), and having this kind of technical documentation would help!

**Comment by leviport** [comment]
Still in progress, but here is the motherboard manual: https://www.asus.com/us/Motherboards/PRIME-X299-DELUXE-II/

Yes, it should support a second GPU as long as the PSU you order will support it. The default 1000W, and the A6000 has a TDP of 300W, so two of them should be just about okay. If you want to be on the safe side, you can also upgrade the PSU.

Also, questions like that are ones that our sales team would be happy to help with.

**Comment by jacobgkau** [comment]
Not planned; we documented r3 instead, and we're up to r5-n3 now.
