### ISSUE TITLE
serw12 contradictory information

### ISSUE THREAD

**Issue by yochananmarqos** [system76/tech-docs#58]
The [README](https://tech-docs.system76.com/models/serw12/README.html) and [repairs](https://tech-docs.system76.com/models/serw12/repairs.html) contradict each other. The repairs page is correct.

> Storage
> M.2 SSD (slot 1): PCIe NVMe Gen 2
> M.2 SSD (slot 2): PCIe NVMe Gen 3 or SATA III

> The slot closest to the fan supports either PCIe NVMe Generation 3 or SATA III. The slot closest to the battery supports PCIe > NVMe Generation 2 only. (PCIe NVMe Generation 3 drives will work at slower speeds in the Generation 2 slot.)

The slot closest to the ~~battery~~ fan is slot 1, right? :wink: 

```
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     S59ANM0NB10302Y      Samsung SSD 970 EVO Plus 1TB             1         635.17  GB /   1.00  TB    512   B +  0 B   2B2QEXM7
/dev/nvme1n1     2041B2807395         WDC WDS100T2B0C-00PXH0                   1           1.00  TB /   1.00  TB    512   B +  0 B   211070WD
                  
```

**Comment by jacobgkau** [comment]
After confirming the slot information and what's currently listed, everything you're quoting is correct and nothing is being contradicted.

Here is a new photo showing the labels on both slots:

![P1030456](https://user-images.githubusercontent.com/7199422/107902500-d7bced00-6f03-11eb-9d64-eea334383437.jpg)

As labeled, Slot 1 (closest to the battery) supports PCIe only. Slot 2 (closest to the fan) supports PCIe and SATA. So:

> M.2 SSD (slot 1): PCIe NVMe Gen 2
> M.2 SSD (slot 2): PCIe NVMe Gen 3 or SATA III

This is correct.

> The slot closest to the fan supports either PCIe NVMe Generation 3 or SATA III.

This is correct.

> The slot closest to the battery supports PCIe NVMe Generation 2 only.

This is correct. Furthermore, the repairs page states higher up:

> Slot 1 supports PCIe NVMe Generation 2, while Slot 2 supports either SATA III or PCIe NVMe Generation 3.

This is also correct. What is the problem?

**Comment by yochananmarqos** [comment]
Oops, typo. First post corrected.

> The slot closest to the ~~battery~~ fan is slot 1, right? :wink: 

The slot closest to the fan is slot 1 and the slot closest the battery is slot 2. Correct?

Therefore, this is correct:

> The slot closest to the fan supports either PCIe NVMe Generation 3 or SATA III. The slot closest to the battery supports PCIe > NVMe Generation 2 only. (PCIe NVMe Generation 3 drives will work at slower speeds in the Generation 2 slot.)

...and this is not:

> M.2 SSD (slot 1): PCIe NVMe Gen 2
> M.2 SSD (slot 2): PCIe NVMe Gen 3 or SATA III

> Slot 1 supports PCIe NVMe Generation 2, while Slot 2 supports either SATA III or PCIe NVMe Generation 3.

**Comment by jacobgkau** [comment]
> The slot closest to the ~battery~ fan is slot 1, right?

I'm sorry, this is not correct. Please see the photo I posted. The top slot, closest to the fan, is labeled `J_SSD2` on the motherboard. The bottom slot, closest to the battery, is labeled `J_SSD1`.

It sounds like you thought the slots were ordered differently based on the names the drives are reporting as in your OS. Numbered drive names are determined at boot and should not be used as a long-term identifier (this is why Pop uses UUIDs in its default `/etc/fstab` file instead of partition numbers.

**Comment by yochananmarqos** [comment]
Oh, I see. Sorry about the false report then.
