### ISSUE TITLE
lemp9: external overview, internal overview, and service manual

### ISSUE THREAD

**Issue by leviport** [system76/tech-docs#7]
The ones @system76/support made for the Adder are very good, and I think this sort of thing should be the goal for all models.

External overview: https://github.com/system76/tech-docs/blob/adder-ws-initial/src/models/addw1/external-overview.md

Internal overview: https://github.com/system76/tech-docs/blob/adder-ws-initial/src/models/addw1/internal-overview.md

Service manual: https://github.com/system76/tech-docs/blob/adder-ws-initial/src/models/addw1/repairs.md

**Comment by jacobgkau** [comment]
This was completed in https://github.com/system76/tech-docs/pull/15.
