### ISSUE TITLE
lemp10: charging information

### ISSUE THREAD

**Issue by ahoneybun** [system76/tech-docs#73]
The computer specs states USB-C power rated at 20V/65W - 20V/100W so this should be in the tech-docs.

**Comment by jacobgkau** [comment]
@ahoneybun Where are you seeing the maximum wattage listed? The Galago and Darter pages just state the minimum wattage, so that's what we would naturally do for the Lemur if what's currently there isn't clear enough.

**Comment by jacobgkau** [comment]
Aaron told me he got this information from an employee at an upstream hardware supplier. I think we should list the minimum wattage to match other models.
