### ISSUE TITLE
gaze16 17.3": Back panel screws are not the same length.

### ISSUE THREAD

**Issue by rellimmot** [system76/tech-docs#88]
see: https://tech-docs.system76.com/models/gaze16/repairs.html

Steps to remove the bottom cover:
Follow the steps above to remove the battery.
Remove the bottom panel screws.
On the 15" model (pictured below):
There are 16 screws total.
The two back corner screws (highlighted red below) are slightly longer than the rest.
The silver hinge screw (highlighted cyan below) is slightly shorter than the rest.
On the 17" model:
There are 17 screws total.
**All screws are the same length.**

The screws are different lengths (one 6mm) on the unit I received. I'm putting little retaining clips on the screws since its ridiculous to have so many screws (_of different lengths_), to have to pop plastic clips off (thus screws go flying if you don't remove them) and have them not be captive (note for product improvement). At least that's my little gripe since I do swap drives semi frequently.

Please clarify where to place shorter screw in the manual. There is a lot of long screws and a few short ones. I believe the 6mm one is the one next to the battery connector but I'm not 100% sure since, well, I'm guessing. When y'all start making your own laptops we want captive screws! ;) 

<3

**Comment by jacobgkau** [comment]
@rellimmot If you only have one screw shorter than the rest, you're correct that it should go next to the battery connector. We'll get this updated.
