### ISSUE TITLE
Missing instructions for oryp5

### ISSUE THREAD

**Issue by remcohaszing** [system76/tech-docs#91]
I want to clean my oryp5, but I couldn’t remove the bottom cover.

I found the tech docs, but they only contain instructions for the oryp6 and oryp7. Could you add intructions for the oryp5 as well?

**Comment by jacobgkau** [comment]
The oryp5 was released before the tech-docs website was created. We currently add all new products to tech-docs at launch, but there are not currently plans to add the oryp5. However, there is a PDF service manual for the oryp5 here: https://raw.githubusercontent.com/system76/docs/master/static/service-manuals/pdfs/Oryx/oryp5-service-manual.pdf

**Comment by joemcl** [comment]
@jacobgkau  thanks and what's the link to the manual for the Oryx Pro 1? Also can the manuals for older models please be linked to from https://tech-docs.system76.com/ , that would be great.

**Comment by leviport** [comment]
They're all linked from the service manual support document here: https://support.system76.com/articles/guides
